import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: main.ts and src/** — see repository for original TypeScript sources.
If you want to view the source, please visit the plugin's repository.
*/
`;

const production = process.argv[2] === 'production';

const context = await esbuild.context({
    banner: {
        js: banner
    },
    entryPoints: ['main.ts'],
    bundle: true,
    platform: 'node',
    target: 'node18',
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
        // НЕ добавляем @grpc/* сюда — они будут забандлены
    ],
    // Плагин для явного разрешения модулей
    plugins: [
        {
            name: 'resolve-grpc',
            setup(build) {
                build.onResolve({ filter: /^@grpc\/grpc-js$/ }, () => {
                    return { path: require.resolve('@grpc/grpc-js') };
                });
                build.onResolve({ filter: /^@grpc\/proto-loader$/ }, () => {
                    return { path: require.resolve('@grpc/proto-loader') };
                });
            },
        },
    ],
    // Загрузка .proto файлов как текста (если они используются)
    loader: {
        '.proto': 'text',
    },
    format: 'cjs',
    logLevel: 'info',
    sourcemap: production ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: production
});

if (production) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}