import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: main.ts and src/** — see repository for original TypeScript sources.
If you want to view the source, please visit the plugin's repository.
*/
`;

const production = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner
	},
	entryPoints: ['main.ts'],
	bundle: true,
	// obsidian, electron и стандартные Node/Electron-модули не бандлятся —
	// они предоставляются рантаймом хоста (Obsidian) и не должны попадать в main.js.
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: production
});

if (production) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}